theme: jekyll-theme-minimal
title: Lydia Seils - Selected Works
description: Name: Lydia Seils
            Hi, I am currently a M.S. Architecture student at Georgia Institute of Technology. 
            Through my B.Arch program at Rensselaer Polytechnic Institute, I have been able to become proficent in architectural design, while fine tuning technical skills. 
            In addition to my architecture expertise, I have also dicovered my computational interests and coding skills. 
            My designation in my grad program is in computation design, where I am able to explore my interests in computational design, and how design tools affects the architectural processes. 
            Work shown in this collection includes contemporary arhitectural projects as well as different design aids I have created. 
            This portfolio contains the design work of

            Lydia Seils.
            
            Lydia Seils Works/Portfolio @2024
            M.S. Architecture, designation in Computational Design (ongoing)
            Georigia Institute of Technology
            
            Lydiamseils@gmail.com
            315.651.2311
